### PR TITLE
Update production 120516

### PR DESCRIPTION
**Pull request by akainic**

### CODE REVIEW

**Comment by akainic** [comment]
Doing a production deploy of  HCA this afternoon. Assiging @markolson, but could @knkski and @lihanli also take a quick look to make sure their most recent changes are reflected here?

**Comment by lihanli** [comment]
it's missing the json schema validation changes but it shouldn't matter if frontend has the validations

**Comment by akainic** [comment]
Which json schema validation changes @lihanli? Do you mind linking to the PR that had those changes if you can find it?

**Comment by lihanli** [comment]
it's these 2
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/43
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/42

frontend should already have these validations in production so unless someone makes a submission with curl or something we shouldn't get any errors

**Comment by akainic** [comment]
@lihanli just pulled in your latest schema update, so we should be good now.

**Review by lihanli — APPROVED** [review]

**Comment by akainic** [comment]
Hit an error because the schema wasn't updated. Closing for now until I can fix the schema.

**Review by markolson — APPROVED** [review]

**Pull request merged**
