### PR TITLE
tiny fix + comments for applicationInfo

### PR DESCRIPTION
**Pull request by alexose**

### CODE REVIEW

**Comment by alexose** [comment]
I put this in a separate PR because I wasn't sure about the implications of using the time on the server to determine `appDate`.

Is there a chance that it'll cause problems if there's an off-by-one error due to timezones?

**Comment by alexose** [comment]
Also, I noticed that we pulled in moment.js on the validation side of things.  So we can probably get rid of https://github.com/department-of-veterans-affairs/healthcare-application/blob/master/src/server/enrollment-system.js#L83-L96

**Comment by robbiethegeek** [comment]
LGTM

**Comment by robbiethegeek** [comment]
is there someone that can answer your Question @alexose  that you are thinking of regarding the timezones?

**Comment by awong-dev** [comment]
@alexose I believe this is an audit timestamp and that we really have no sane choice other than to use server timestamp.  What we can ensure in moment is that we're always stamping with a consistent timezone that doesn't have daylight savings as opposed to whatever the server is configured with.

The right thing to do is to ping Joshua.

**Comment by awong-dev** [comment]
@alexose Let's merge this in. I will create bug for following up about timezones.

**Comment by robbiethegeek** [comment]
bump, where does this live in the newly refactored API?

**Comment by awong-dev** [comment]
@robbiethegeek same place.

**Comment by robbiethegeek** [comment]
Just updated branch can you squash and then will merge in if all is good.

**Pull request merged**
