### PR TITLE
HCA UI Fixes

### PR DESCRIPTION
**Pull request by crwallace**
This closes:
- 459: Disable button if a user gets "Send Failed"
- 437: Hide spouse support if you lived with spouse
- 463: Add OMB control number

### CODE REVIEW

**Comment by akainic** [comment]
LGTM! The only question I have is about the placement of the OMB number. Does it need to go in the header for that page? Seems like it might be better at the bottom of the introduction text or right below the header, something not so prominent.

**Comment by crwallace** [comment]
I thought in the header made the most sense since it is an OMB number for the form. They are realted and any other place I put it felt random and without context.

**Comment by akainic** [comment]
Are OMB numbers used by veterans or other people that will use this form to identify the form? Does it mean something to those people? I'm not totally clear what it is used for, other than it's relation to PRA.

**Comment by akainic** [comment]
Let's merge as is and we can revisit the question about OMB numbers.

**Pull request merged**
