### PR TITLE
rate limit healthcheck/es calls

### PR DESCRIPTION
**Pull request by alexose**
This prevents us from accidentally DDOSing `healthcheck/es` if we start hitting the endpoint a lot.

Related to https://github.com/department-of-veterans-affairs/devops/issues/307

### CODE REVIEW

**Comment by akainic** [comment]
LGTM, but I would prefer if @robbiethegeek could also take a look at this.

**Comment by akainic** [comment]
@alexose how are we currently using the status endpoint? Is this what you configured in AWS?

**Comment by alexose** [comment]
It's not used by anything at the moment.  Ideally, we'd use it in two places:
- The frontend should check it on page load in order to display a message if ES is down
- AWS should check it every so often to maintain a record of ES uptime

**Comment by akainic** [comment]
Gotcha. This seems like a valuable thing to have in place anyway. We probably want to configure those other uses at some point soon as well. LGTM!

**Pull request merged**
