### PR TITLE
Use browserHistory instead of hashHistory.

### PR DESCRIPTION
**Pull request by awong-dev**
fixes
https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/207.

### CODE REVIEW

**Comment by awong-dev** [comment]
@robbiethegeek for the node.js express change.

**Comment by robbiethegeek** [comment]
Express change looks fine. Without tests please just test manually to confirm. Once that is confirmed LGTM on server.js

**Comment by akainic** [comment]
Looks good except that the redirect to `/introduction` in HealthCareApp isn't working. If I go to just localhost:3000/healthcare/apply I get a 404.

**Comment by awong-dev** [comment]
@akainic Nice catch!

I fixed.

**Comment by awong-dev** [comment]
Rebased and fixed router ordering problems so now this should all work.

**Comment by awong-dev** [comment]
Reassigning to @akainic to verify that my fix actually worked for her. If it works, let's merge.

**Comment by akainic** [comment]
~~Works for me now!~~ Not yet, was too excited

**Comment by awong-dev** [comment]
Okay, the problem is `npm run watch` is broken cause the hot reload path has a different server configruation. See the `historyApiFallback` option to the dev server...I need to figure out how to weave that through right.

**Comment by awong-dev** [comment]
Apparently the solution is `historyApiFallback: true` to make webpack dev server do the equiv of serving the index page for every 404.

Yay?

Okay, this should work now.  @akainic, can you test in both `npm run watch` mode as well as `npm run webpack-noopt; npm run start` mode?  Make sure to do a `killall npm; killall node` to be sure...also might delete everything in `generated` before running `npm run webpack-noopt`.

**Comment by akainic** [comment]
@awong-dev It worked for me with both `npm run watch` and `npm run webpack-noopt; npm run start`!

**Pull request merged**
