### PR TITLE
Add county

### PR DESCRIPTION
**Pull request by akainic**

### CODE REVIEW

**Comment by markolson** [comment]
Can you modify one of the json files in `test/data/conformance` to include a county as well? You'll have to add the value to the corresponding XML file, but it'll let us make sure we're serializing it correctly.

**Comment by leannammiller** [comment]
@markolson - status?

**Comment by markolson** [comment]
I can work on this this week to resolve the merge conflicts and add some tests

**Comment by leannammiller** [comment]
@markolson - status update? :)

**Comment by leannammiller** [comment]
@akainic - who should get this now that mark is out?

**Comment by leannammiller** [comment]
@leanna will check with Josh Faulkner if we need to include a field for the address as per ES

**Comment by leannammiller** [comment]
@akainic not required. close?

**Comment by akainic** [comment]
Yep. CLosing.

**Pull request closed without merging**
