### PR TITLE
Fix schema errors related to disclosure

### PR DESCRIPTION
**Pull request by jbalboni**
Related to [501](https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/501)

This is an attempt at fixing the schema errors. Needs some tests, but thought I'd get some feedback on the changes first.

### CODE REVIEW

**Comment by akainic** [comment]
This is really strange, when I test it locally, stating that I am married but I do not consent to providing my financial information, I get a different schema error when submitting:

```
TypeError: Cannot read property 'city' of undefined
    at formatAddress (/Users/annekainic/Desktop/coding/healthcare-application/src/server/enrollment-system.js:49:18)
    at spouseToAssociation (/Users/annekainic/Desktop/coding/healthcare-application/src/server/enrollment-system.js:1052:16)
    at veteranToAssociationCollection (/Users/annekainic/Desktop/coding/healthcare-application/src/server/enrollment-system.js:1146:18)
    at veteranToSummary (/Users/annekainic/Desktop/coding/healthcare-application/src/server/enrollment-system.js:1276:19)
    at veteranToSaveSubmitForm (/Users/annekainic/Desktop/coding/healthcare-application/src/server/enrollment-system.js:1322:26)
    at submitApplication (/Users/annekainic/Desktop/coding/healthcare-application/src/server/routes/application.js:45:33)
```

It's confusing because it must be failing because `veteran.spouseAddress` isn't set, but it shouldn't even be calling `formatAddress` from `spouseToAssociation` because we're first checking that `_.includes(['Married', 'Separated'], veteran.maritalStatus) && veteran.discloseFinancialInformation`.

**Comment by jbalboni** [comment]
@akainic Yeah, that's the error I was getting that error after my front end changes but before the backend ones. It seemed like I was having trouble getting the Node backend to see my changes using the watch task, so I wonder if it's using the old code?

**Comment by akainic** [comment]
Looks like restarting my server fixed that error!

**Review by akainic — APPROVED** [review]
LGTM!

**Comment by jbalboni** [comment]
@markolson Any other backend tests I should write?

**Comment by markolson** [comment]
I'd find one of the existing conformance tests to poke at, or to make a new one that triggers this new logic

**Comment by jbalboni** [comment]
@markolson It looks like there are conformance tests with discloseFinancialInformation set to false and that don't have the spouse info already. Though I'm not sure why they weren't failing.

**Review by markolson — APPROVED** [review]

**Review by akainic — COMMENTED** [review]
LGTM!

**Pull request merged**
