### PR TITLE
Make a place for questions and answers.

### PR DESCRIPTION
**Pull request by joesoftware**

### CODE REVIEW

**Comment by markolson** [comment]
My initial thought is that this may be over-specific, but having the baseline may be handy if anyone else hits this problem.. I think the more important thing to include is how to _get_ to that baseline, especially if something is wrong.

**Comment by akainic** [comment]
I agree with @markolson that this seems very specific. Perhaps instead something simply saying, "If you encounter this problem, it may be because your development environment needs to have the following version of xcode", with "this problem" being the problem you encountered.

**Comment by joesoftware** [comment]
Reframed this as suggested.

**Comment by markolson** [comment]
I'd maybe move it to the docs/ folder, then 👍 from me

**Comment by joesoftware** [comment]
Sounds good Mark. I'll move the file, update the branch then merge with master.

**Pull request merged**
