### PR TITLE
Update to the latest facility list.

### PR DESCRIPTION
**Pull request by robbiethegeek**
Closes ticket #301

### CODE REVIEW

**Comment by crwallace** [comment]
There are still some duplicates in this list. Only looked quickly but under FL I still see two `'ORLANDO VA HEALTHCARE CENTER NHCU'`.

**Comment by crwallace** [comment]
Also I just noticed this as well `{ value: '673PA', label: 'THIS ENTRY ENTERED IN ERROR' },`

**Comment by robbiethegeek** [comment]
@akainic @staceylanger not sure how you want to handle this?  I think there may be dupes but they have different codes and then what about the error'd ones?

**Comment by crwallace** [comment]
Also...looks like some of these might not be medical facilities/hospitals `{ value: '5099AA', label: 'AUGUSTA NURSING HOME' },`

**Comment by akainic** [comment]
@robbiethegeek and @crwallace sounds like a question for Mehedi. I will follow up with him on this.

**Comment by crwallace** [comment]
This looks much better!

**Comment by akainic** [comment]
LGTM! Will merge once tests pass.

**Pull request merged**
