### PR TITLE
Fix typo in README (machien -> machine)

### PR DESCRIPTION
**Pull request by daguar**
✊

### CODE REVIEW

**Comment by robbiethegeek** [comment]
LGTM thanks! Restarting the Travis tests if they pass will merge in :)

**Comment by daguar** [comment]
If I'm reading the CI log correctly, it looks like SauceLabs might need credentials that aren't coming when I have a branch on my fork?

**Comment by daguar** [comment]
Oh odd it looks like Sauce creds are included in the Travis config, so probably a failure to establish a Selenium connection. (Yay Selenium life! I feel this every day. :D )

**Comment by daguar** [comment]
It looks like this is a CI configuration issue (Sauce Labs tests will always fail on external PRs) — I've written up what's going on and some possible ways to address it in a new issue for discussion https://github.com/department-of-veterans-affairs/healthcare-application/issues/225

**Comment by akainic** [comment]
Closing and reopening a new PR to make this fix.

**Pull request closed without merging**
