### PR TITLE
Exclude SpouseFinancials if there's no SpouseFinancial data

### PR DESCRIPTION
**Pull request by markolson**
Previously we were excluding the SpouseFinancial section iff the entire FinancialInfo section was excluded - this makes it a bit more fine-grained.

### CODE REVIEW

**Comment by akainic** [comment]
Just wondering if we want to do the same thing for dependents? Otherwise LGTM!

**Comment by markolson** [comment]
Good catch - I'll write up a test (and possible fix) for that and add it to this PR

**Comment by markolson** [comment]
@akainic this is ready for another look when you have a minute to check over the diffs.

**Comment by akainic** [comment]
LGTM!

**Pull request merged**
